# Before running this code, please manually change the parameters in combine_BTW_and_codon_path_result_HY.py (see readme file)

cp ../___step1__make_codon_configuration_data/codon_configuration_at_extant_nodes.txt codon_configuration_at_extant_nodes.txt
cp ../___step2__estimate_syn_nonsyn_substituion_ratio/joint_probability_of_ancestral_codon_configuration_from_BASEML_and_BTW_wo_configuration_with_stop_codons.txt joint_probability_of_ancestral_codon_configuration_from_BASEML_and_BTW_wo_configuration_with_stop_codons.txt

python3 combine_BTW_and_codon_path_result_HY.py
mv test_out.txt list_of_BTW_ancestor_prob_and_codon_path_prob.txt

perl make_list_of_codon_change_with_probability.pl
perl convert_codon_to_digit_for_list_of_codon_change_ver221215.pl

perl make_list_of_codon_change_with_probability_for_Dm_Ds_fixations_ver221215_codon_digit.pl
perl make_list_of_codon_change_with_probability_for_Dm_Ds_polymorphisms_ver221215_codon_digit.pl
perl make_list_of_codon_change_with_probability_S_N_for_fix_ver221215_codon_digit.pl
perl make_list_of_codon_change_with_probability_S_N_for_poly_ver221215_codon_digit.pl
