cp ../___step1__make_codon_configuration_data/codon_configuration_at_extant_nodes.txt codon_configuration_at_extant_nodes.txt
cp ../___step1__make_codon_configuration_data/joint_probability_of_ancestral_codon_configuration_from_BASEML_and_BTW.txt joint_probability_of_ancestral_codon_configuration_from_BASEML_and_BTW.txt

perl make_joint_prob_anc_cod_config_list_wo_configuration_with_stop_codons_ver221215.pl
perl make_joint_prob_anc_cod_config_list_only_with_single_or_no_change_per_path_ver221215.pl
perl make_list_of_codon_change_with_probability_for_dNdS_calculation_ver221215.pl
perl make_list_of_codon_change_with_probability_S_N_for_fix_for_dNdS_calculation_ver221215.pl
perl count_Dn_Ds.pl
perl make_list_of_N_S_at_ms_and_ye_node.pl